dist: trusty
sudo: false
language: cpp

if: branch = master

before_install:
- eval "${MATRIX_EVAL}"

os:
  - linux
  - osx

jobs:
  include:
    - stage: "Test"
      osx_image: xcode10
      osx_image: xcode9.4
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
      env:
      - MATRIX_EVAL=""
      script:
      - mkdir build-travis
      - cd build-travis
      - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_TEST=ON
      - make -j3
      - ./Simple-Socket-tester.run
      
    - stage: "Coverage"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - lcov
      env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
      - mkdir build-travis
      - cd build-travis
      - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
      - make Simple-Socket-Coverage
      after_success:
      - gem install coveralls-lcov
      - coveralls-lcov Simple-Socket-Coverage.info.cleaned
