dist: trusty
sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-7
          packages:
          - clang-7
          - lldb-7
          - lld-7
          - libc++-7-dev
          - libc++abi-7-dev
      env:
      - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - os: linux
      sudo: true
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-8
          - sourceline: "http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main"
            key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
          - clang-8
          - lldb-8
          - lld-8
          - libc++-8-dev
          - libc++abi-8-dev
      env:
      - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL=""

    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL=""
        
before_install:
    - eval "${MATRIX_EVAL}"

# require the branch name to be master
if: branch = master

script:
- mkdir build-travis
- cd build-travis
- cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
- make -j3
- cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug -DSIMPLE_SOCKET_TEST=ON
- make -j3
- ./Simple-Socket-tester.run
