dist: trusty
sudo: false
language: cpp

jobs:
  include:
    - stage: "Build"
      script:
      - echo "Build stage"
    - stage: "Test"
      script:
      - echo "Test stage"
    - stage: "Coverage"
      env:
      - COVERALL="ON"
      script:
      - echo "Coverage stage"
      after_success:
      - if [[ "$COVERALL" == "ON" ]]; then
          echo "privatee coverage...";
        fi;
        
before_install:
    - eval "${MATRIX_EVAL}"

# require the branch name to be master
if: branch = master

after_success:
- if [[ "$COVERALL" == "ON" ]]; then
    echo "Running coverage test global...";
  fi;
