dist: trusty
sudo: false
language: cpp

if: branch = master

before_install:
- eval "${MATRIX_EVAL}"
  
jobs:
  include:
    - stage: "Test"
      matrix:
        include:
        - os: osx
          osx_image: xcode10
        - os: osx
          osx_image: xcode9.4
      env:
      - MATRIX_EVAL=""
      script:
      - mkdir build-travis
      - cd build-travis
      - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_TEST=ON
      - make -j3
      - ./Simple-Socket-tester.run
      
    - stage: "Coverage"
      matrix:
        include:
        - os: linux
          addons:
            apt:
              sources:
              - ubuntu-toolchain-r-test
              packages:
              - g++-7
              - lcov
      env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
      - mkdir build-travis
      - cd build-travis
      - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
      - make Simple-Socket-Coverage
      after_success:
      - gem install coveralls-lcov
      - coveralls-lcov Simple-Socket-Coverage.info.cleaned
