dist: trusty
language: cpp

if: branch = master

before_install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build-travis
- cd build-travis
- cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUSE_LIBCXX=ON  -DSIMPLE_SOCKET_TEST=ON
- make -j3
- ./Simple-Socket-Tester.run
      
jobs:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        packages:
        - clang-7
        - lldb-7
        - lld-7
        - libc++-7-dev
        - libc++abi-7-dev
    env:
    - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
  
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  
  - os: osx
    osx_image: xcode10
    env:
    - MATRIX_EVAL=""
  
  - os: osx
    osx_image: xcode9.4
    env:
    - MATRIX_EVAL=""
  
  - stage: "Coverage"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - lcov
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug -DSIMPLE_SOCKET_EXAMPLES=OFF -DSIMPLE_SOCKET_COVERAGE=ON
    - make coverage
    after_success:
    - gem install coveralls-lcov
    - cat coverage.info.cleaned
    - cat coverage/src/index.html
    - coveralls-lcov coverage.info.cleaned
  
  - stage: "Legacy"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_EXAMPLES=OFF
  
  - stage: "Legacy"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - lldb-4.0
        - lld-4.0
        - libc++1
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUSE_LIBCXX=ON -DSIMPLE_SOCKET_EXAMPLES=OFF
  
